### ISSUE TITLE
Filter by namespace in Topic list with tagged pages

### ISSUE THREAD

**Issue by tangotribe** [dokufreaks/plugin-pagelist#121] opened 2021-02-10 18:18 UTC
Suppose I have namespaces _draft_ and _published_. I will be giving pages appropriate tags regardless of their draft status.

I want to use **Topic** to create an index page showing all the **published** pages (no draft pages) with tags.

How can I most easily do this? If not, can that capability be added?

**Comment by Klap-in** [comment] 2023-08-25 20:12
Duplicate of #148

**Closed** 2023-08-25 23:16 UTC
Labels: feature request
