### ISSUE TITLE
Can there be a way to use pagination the listings?

### ISSUE THREAD

**Issue by Hitch42** [dokufreaks/plugin-pagelist#117] opened 2020-02-06 19:25 UTC
When displaying a group of pages, by namespace or tag or such, the table will list every page in that category. In some instances, this can lead to a table several hundred rows long. The ability to use pagination in the results, so that only a certain amount are shown at a time, would be very useful. Maybe it could be displayed as a [DataTable](https://datatables.net/) or be made compatible with the [DataTables](https://www.dokuwiki.org/plugin%3Adatatables) plugin.

**Comment by Klap-in** [comment] 2023-08-25 20:15
Duplicate of #138

**Closed** 2023-08-25 23:16 UTC
Labels: feature request
